LMS/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace LMS.Controllers
{
    public class TeacherController : Controller
    {
        public IActionResult teacher_index()
        {
            return View("./Views/Teacher/main_page.cshtml");
        }
    }
}

LMS/Views/Shared/MasterLayout.cshtml
 <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School Management</title>

    <link href="~/lib/jquery-ui/themes/base/jquery-ui.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/my.css" rel="stylesheet" />

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

</head>
<body>

    @Html.Partial("_MenuBar")

    <div class="container body-content">
        @RenderBody()
    </div>
    @RenderSection("Scripts", required: false)


</body>
</html>

LMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LMS</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LMS</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Home">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
       @RenderBody()
        <hr />
        @*<footer>
            <p>&copy; 2020 - LMS</p>
        </footer>*@
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

LMS/Views/Shared/_menubar.cshtml
<!DOCTYPE html>

<head>
    <link href="~/css/navigation.css" rel="stylesheet" />
</head>
<body>
    <nav>
        <ul>
            <li><a asp-area="" asp-controller="Home" asp-action="Home">Al Naseem</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Add_Students_In_Bulk">Add Student Data</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Grades">Grades</a></li>
            <li><a asp-area="" asp-controller="Student" asp-action="Print_Previous_Result">Previous Result</a></li>
            <li>
                <a asp-area="" asp-controller="Teacher" asp-action="teacher_index">Teacher</a>
                <ul>
                    <li><a asp-area="" asp-controller="Teacher" asp-action="teacher_index">Add Teacher</a></li>
                    <li><a asp-area="" asp-controller="Teacher" asp-action="teacher_index">Add Salary</a></li>
                </ul>
            </li>
            <li style="float:right"><a asp-area="" asp-controller="Login" asp-action="Logout" style="background-color:red">Logout</a></li>
        </ul>

    </nav>
</body>