LMS/Models/grade.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Models
{
    public class Grade
    {
        
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Grade_Id { get; set; }
        [Required]
        public string Grade_Name { get; set; }
        [Required]
        public string Level { get; set; }
        [Required]
        public string Section_Name { get; set; }
        [Required]
        public string Complete_Grade_Name { get; set; }
        [Required]
        public string Complete_Grade_Name_Arabic { get; set; }
        
    }
}

LMS/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LMS.Models;
using Microsoft.AspNetCore.Mvc;

namespace LMS.Controllers
{
    public class CommonController : Controller
    {
        private Data.DataContext _db;
        public CommonController(Data.DataContext db)
        {
            _db = db;
        }
        public IActionResult GoBack(string Url)
        {
            return Redirect(Url);
        }

        public JsonResult CheckGradeAvailability(string g_na, string s_na)
        {
            var result = _db.Grades.Any(x => x.Grade_Name == g_na && x.Section_Name == s_na);
            if (result)
            { return Json(1); }
            else { return Json(0); }
          
            
        }
    }
}

LMS/Controllers/GradeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LMS.Models;
using Microsoft.AspNetCore.Mvc;

namespace LMS.Controllers
{
    public class GradeController : Controller
    {
        private Data.DataContext _db;
        public GradeController(Data.DataContext db)
        {
            _db = db;
        }
        [HttpPost]
        public IActionResult Index(Grade grade)
        {
            if (grade.Level != "Please Select")
            {
                var a = grade.Level + "-" + grade.Grade_Name + " (" + grade.Section_Name + ")";
                if (_db.Grades.Any(x => x.Complete_Grade_Name == a))
                {
                    ViewBag.message = "Grade already exist";
                }
                else
                {
                    grade.Complete_Grade_Name = a;
                    grade.Complete_Grade_Name_Arabic = arabic_grade(a);
                    _db.Grades.Add(grade);
                    _db.SaveChanges();
                    ViewBag.message = "Grade saved";
                }
            }
            else
            {
                ViewBag.message = "Select Level";
            }
            var section = _db.Sections.ToList();
                ViewBag.section = section;
                var g = _db.Grades.ToList().OrderBy(x => x.Grade_Name);
                ViewBag.grade = g;
            
            

            return View("./Views/Grades/Grades.cshtml", new Models.Grade());

        }

        public string arabic_grade(string a)
        {
            //////////////////////////////KG-1/////////////////////////////////////
            if (a == "KG-1 (A)")
            {
                return "(روضة أول (ا";
            }
            else if (a == "KG-1 (B)")
            {
                return "(روضة أول (ب";
            }
            else if (a == "KG-1 (C)")
            {
                return "(روضة أول (ج";
            }
            else if (a == "KG-1 (D)")
            {
                return "(روضة أول (د";
            }

            /////////////////////////////KG-2/////////////////////
            else if (a == "KG-2 (A)")
            {
                return "(روضة ثاني (ا";
            }
            else if (a == "KG-2 (B)")
            {
                return "(روضة ثاني (ب";
            }
            else if (a == "KG-2 (C)")
            {
                return "(روضة ثاني (ج";
            }
            else if (a == "KG-2 (D)")
            {
                return "(روضة ثاني (د";
            }
            /////////////////////////////////KG-3//////////////////////////////
            else if (a == "KG-3 (A)")
            {
                return "(روضة ثالث (ا";
            }
            else if (a == "KG-3 (B)")
            {
                return "(روضة ثالث (ب";
            }
            else if (a == "KG-3 (C)")
            {
                return "(روضة ثالث (ج";
            }
            else if (a == "KG-3 (D)")
            {
                return "(روضة ثالث (د";
            }
            /////////////////////////////////////Grade 1/////////////////////////////
            else if (a == "Grade-1 (A)")
            {
                return " (الصف الاول الابتدائي (ا";
            }
            else if (a == "Grade-1 (B)")
            {
                return "(الصف الاول الابتدائي (ب";
            }
            else if (a == "Grade-1 (C)")
            {
                return "(الصف الاول الابتدائي (ج";
            }
            else if (a == "Grade-1 (D)")
            {
                return "(الصف الاول الابتدائي (د";
            }
            /////////////////////////////////////Grade-2/////////////////////////////
            else if (a == "Grade-2 (A)")
            {
                return " (الصف الثاني الابتدائي (ا";
            }
            else if (a == "Grade-2 (B)")
            {
                return "(الصف الثاني الابتدائي (ب";
            }
            else if (a == "Grade-2 (C)")
            {
                return "(الصف الثاني الابتدائي (ج";
            }
            else if (a == "Grade-2 (D)")
            {
                return "(الصف الثاني الابتدائي (د";
            }
            ////////////////////////////////////////////Grade-3//////////////////////
            else if (a == "Grade-3 (A)")
            {
                return " (الصف الثالث الابتدائي (ا";
            }
            else if (a == "Grade-3 (B)")
            {
                return "(الصف الثالث الابتدائي (ب";
            }
            else if (a == "Grade-3 (C)")
            {
                return "(الصف الثالث الابتدائي (ج";
            }
            else if (a == "Grade-3 (D)")
            {
                return "(الصف الثالث الابتدائي (د";
            }
            ////////////////////////////////////////////Grade-4//////////////////////
            else if (a == "Grade-4 (A)")
            {
                return " (الصف الرابه الابتدائي (ا";
            }
            else if (a == "Grade-4 (B)")
            {
                return "(الصف الرابه الابتدائي (ب";
            }
            else if (a == "Grade-4 (C)")
            {
                return "(الصف الرابه الابتدائي (ج";
            }
            else
            {
                return "(الصف الرابه الابتدائي (د";
            }
        }
    }
}

LMS/Views/Grades/Grades.cshtml
@model  LMS.Models.Grade
@{
    ViewData["Title"] = "Grades";
}



<body>
    <h2 style="margin:30px">Grades Information</h2>
    <h1 id="message">@ViewBag.message</h1>

    @using (Html.BeginForm("Index", "Grade", FormMethod.Post))
    {
        <div class="container">

            <button type="button" class="collapsible">Add New Grade</button>
            <div class="content">
                <br />
                <label class="col-lg-3">Grade Number</label>
                <input placeholder="Enter Grade Number" id="g_n" name="Grade_Name" required>
                <select name="Level">
                    <option>Please Select</option>
                    <option>KG</option>
                    <option>Grade</option>
                </select>
                <br />
                <br />

                <div>
                    <label class="col-lg-3">Select Section</label>
                    @foreach (var s in ViewBag.section)
                    {
                        <label class="radio-inline">
                            <input type="radio" id="s_n" name="Section_Name" value="@s.Section_Name">@s.Section_Name
                        </label>
                    }
                </div>
                <br />
                <br />
                <span id="status"></span>
                <input type="submit" id="add_grade" name="add_grade" value="Add" style="background-color:grey; width:100px" />
                <br />
                <br />
            </div>

            <button type="button" class="collapsible">View Grades</button>
            <div class="content">
                <br />
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Grade
                            </th>
                            <th>
                                Section
                            </th>
                            <th>
                                Grade in English
                            </th>
                            <th>
                                Grade in Arabic
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var v in ViewBag.grade)
                        {
                        <tr>
                            <td>@v.Grade_Name</td>
                            <td>@v.Section_Name</td>
                            <td>@v.Complete_Grade_Name</td>
                            <td>@v.Complete_Grade_Name_Arabic</td>
                        </tr>
                        }

                    </tbody>
                </table>

            </div>

        </div>

    }

    <script>
        var coll = document.getElementsByClassName("collapsible");
        var i;

        for (i = 0; i < coll.length; i++) {
            coll[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var content = this.nextElementSibling;
                if (content.style.display === "block") {
                    content.style.display = "none";
                } else {
                    content.style.display = "block";
                }
            });
        }

    </script>
    <script>
        function UserCheck(e) {
            $("#status").html("Checking...");



        $.post("@Url.Action("CheckGradeAvailability", "Common")",
            {
                g_na: $("#g_n").val(),
                s_na: $("#s_n").val()
            },
            function (data) {
                alert(data)
            if (data == 0) {
                $("#status").html('<font color="Green">Available !. you can take it.</font>');
                $("#g_n").css("border-color", "Green");
                return true;
            }
            else {
                $("#status").html('<font color="Red">That name is taken.Try Another.</font>');
                $("#g_n").css("border-color", "Red");
                event.preventDefault();
                return false;


            }
        });
        }


        @*function check_user() {
            var g_na = $("#g_n").val();
            var s_na = $("#s_n").is(':checked');
            alert(s_na);
            if ($("#g_n").length > 0 && s_na) {
                alert(g_na);
                $("#status").html("Checking...");
                $.post("@Url.Action("CheckGradeAvailability", "Common")",
                    {
                        g_na: g_na,
                        s_na: $("#s_n").val()
                    },
                    function (data) {
                        alert(data)
                        if (data == 0) {
                            $("#status").html('<font color="Green">Available !. you can take it.</font>');
                            $("#g_n").css("border-color", "Green");
                            $("#add_grade").attr('disabled', false);

                        }
                        else {
                            $("#status").html('<font color="Red">That name is taken.Try Another.</font>');
                            $("#g_n").css("border-color", "Red");
                            $("#add_grade").attr('disabled', true);
                            $("#add_grade").css('backgroud-color', 'green');
                        }
                    });
            }
            }*@

    </script>
    <script>

        $(document).ready(function () {
            $("#message").show(function () {
                setTimeout(function () {
                    $('#message').fadeOut();
                }, 3000);
            });
        });
    </script>
</body>